version: "3.8"
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
  api:
    build:
      context: api
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./api:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - db
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}